// VALUE = PRISMA ENUM

export const chickenBreed = [
  { value: "marans", label: "Marans" },
  { value: "autre", label: "Autre" },
  { value: "unknown", label: "Inconnue" },
  { value: "leghorn", label: "Leghorn" },
  { value: "isaBrown", label: "Isa Brown" },
  { value: "harco", label: "Harco" },
  { value: "sussex", label: "Sussex" },
  { value: "rhodeIslandRed", label: "Rhode Island Red" },
  { value: "cornish", label: "Cornish" },
  { value: "faverolles", label: "Faverolles" },
  { value: "plymouthRock", label: "Plymouth Rock" },
  { value: "brahma", label: "Brahma" },
  { value: "cochin", label: "Cochin" },
  { value: "orpington", label: "Orpington" },
  { value: "wyandotte", label: "Wyandotte" },
  { value: "sussexTricolor", label: "Sussex Tricolor" },
  { value: "australorp", label: "Australorp" },
  { value: "padoue", label: "Padoue" },
  { value: "houdan", label: "Houdan" },
  { value: "sabelpoot", label: "Sabelpoot" },
  { value: "serama", label: "Serama" },
  { value: "nagasaki", label: "Nagasaki" },
  { value: "gournay", label: "Gournay" },
  { value: "coucouDeRennes", label: "Coucou De Rennes" },
  { value: "gelineDeTouraine", label: "Géline De Touraine" },
  { value: "gauloise", label: "Gauloise" },
  { value: "ardennaise", label: "Ardennaise" },
  { value: "pekin", label: "Pékin" },
  { value: "sebright", label: "Sebright" },
  { value: "chabo", label: "Chabo" },
  { value: "barbuDUccle", label: "Barbu D'Uccle" },
  { value: "bantamDeHollande", label: "Bantam De Hollande" },
];
