import { z } from "zod";

export const animalSchema = z.object({
  id: z.string().uuid().optional(),
  name: z.string(),
  weight: z.number(),
  dateOfBirth: z.date().optional(),
  imgUrl: z.string(),
  sex: z.enum(["male", "female"]),
  race: z.enum([
    "leghorn",
    "isaBrown",
    "harco",
    "sussex",
    "rhodeIslandRed",
    "cornish",
    "faverolles",
    "plymouthRock",
    "brahma",
    "cochin",
    "orpington",
    "wyandotte",
    "marans",
    "sussexTricolor",
    "australorp",
    "padoue",
    "houdan",
    "sabelpoot",
    "serama",
    "nagasaki",
    "gournay",
    "coucouDeRennes",
    "gelineDeTouraine",
    "gauloise",
    "ardennaise",
    "pekin",
    "sebright",
    "chabo",
    "barbuDUccle",
    "bantamDeHollande",
    "autre",
  ]),
});
